
CREATE TABLE DEVICE(
   ID INT NOT NULL AUTO_INCREMENT,
   DEVICE_ID VARCHAR(250) NOT NULL,
   DEVICE_NAME VARCHAR(250),
   DEVICE_STATUS VARCHAR(250),
   PRIMARY KEY (ID)
);

DROP TABLE DEVICE;

