
CREATE TABLE User(
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(250) NOT NULL,
   EMAIL  VARCHAR(250),
   PASSWORD VARCHAR(20),
   ACCESS_KEY VARCHAR(50),
   PRIMARY KEY (ID)
);

DROP TABLE USER;